import { fetchCountries } from '@/apis/fetchCountries'
import CountryPicker from '@/components/CountryPicker'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const regionCountries = await fetchCountries()

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex items-center justify-between flex-row bg-teal-500 p-6 ">
          <span className="font-semibold text-xl tracking-tight  text-white">Sanyam</span>
          <span className="flex-1" />

          <CountryPicker regionCountries={regionCountries} />
        </nav>

        {children}
      </body>
    </html>
  )
}
